amcl:
  ros__parameters:

    use_sim_time: false

    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.2

    base_frame_id: "base_footprint"
    odom_frame_id: "odom"
    global_frame_id: "map"

    scan_topic: scan

    min_particles: 500
    max_particles: 2000

    laser_model_type: likelihood_field

    update_min_d: 0.25
    update_min_a: 0.2

    transform_tolerance: 1.0

    set_initial_pose: false